module.exports = mathSymbols = [
    {
      "character": "&#x221E;",
      "glyph": "∞",
      "asciimath": "oo",
      "name": "infinity",
    },
    {
      "character": "&#x3B1;",
      "glyph": "α",
      "asciimath": "alpha",
      "name": "alpha greek letter",
    },
    {
      "character": "&#x3B2;",
      "glyph": "β",
      "asciimath": "beta",
      "name": "beta greek letter",
    },
    {
      "character": "&#x3B2;",
      "glyph": "β",
      "asciimath": "beta",
      "name": "beta greek letter",
    },
    {
      "character": "&#x3B3;",
      "glyph": "γ",
      "asciimath": "gamma",
      "name": "gamma greek letter",
    },
    {
      "character": "&#x393;",
      "glyph": "Γ",
      "asciimath": "Gamma",
      "name": "capital gamma greek letter",
    },
    {
      "character": "&#x3B4;",
      "glyph": "δ",
      "asciimath": "delta",
      "name": "delta greek letter",
    },
    {
      "character": "&#x394;",
      "glyph": "Δ",
      "asciimath": "Delta",
      "name": "capital delta greek letter",
    },
    {
      "character": "&#x3B5;",
      "glyph": "ε",
      "asciimath": "epsilon",
      "name": "epsilon greek letter",
    },
    {
      "character": "&#x25B;",
      "glyph": "ɛ",
      "asciimath": "varepsilon",
      "name": "varepsilon greek letter",
    },
    {
      "character": "&#x3B6;",
      "glyph": "ζ",
      "asciimath": "zeta",
      "name": "zeta greek letter",
    },
    {
      "character": "&#x3B7;",
      "glyph": "η",
      "asciimath": "eta",
      "name": "eta greek letter",
    },
    {
      "character": "&#x3B8;",
      "glyph": "θ",
      "asciimath": "theta",
      "name": "theta greek letter",
    },
    {
      "character": "&#x398;",
      "glyph": "Θ",
      "asciimath": "Theta",
      "name": "capital theta greek letter",
    },
    {
      "character": "&#x3D1;",
      "glyph": "ϑ",
      "asciimath": "vartheta",
      "name": "vartheta greek letter",
    },
    {
      "character": "&#x3B9;",
      "glyph": "ι",
      "asciimath": "iota",
      "name": "iota greek letter",
    },
    {
      "character": "&#x3BA;",
      "glyph": "κ",
      "asciimath": "kappa",
      "name": "kappa greek letter",
    },
    {
      "character": "&#x3BB;",
      "glyph": "λ",
      "asciimath": "lambda",
      "name": "lambda greek letter",
    },
    {
      "character": "&#x39B;",
      "glyph": "Λ",
      "asciimath": "Lambda",
      "name": "capital lambda greek letter",
    },
    {
      "character": "&#x3BC;",
      "glyph": "μ",
      "asciimath": "mu",
      "name": "mu greek letter",
    },
    {
      "character": "&#x3BD;",
      "glyph": "ν",
      "asciimath": "nu",
      "name": "nu greek letter",
    },
    {
      "character": "&#x3BE;",
      "glyph": "ξ",
      "asciimath": "xi",
      "name": "xi greek letter",
    },
    {
      "character": "&#x39E;",
      "glyph": "Ξ",
      "asciimath": "Xi",
      "name": "capital xi greek letter",
    },
    {
      "character": "&#x3C0;",
      "glyph": "π",
      "asciimath": "pi",
      "name": "pi greek letter",
    },
    {
      "character": "&#x3A0;",
      "glyph": "Π",
      "asciimath": "Pi",
      "name": "capital pi greek letter",
    },
    {
      "character": "&#x3C1;",
      "glyph": "ρ",
      "asciimath": "rho",
      "name": "rho greek letter",
    },
    {
      "character": "&#x3C3;",
      "glyph": "σ",
      "asciimath": "sigma",
      "name": "sigma greek letter",
    },
    {
      "character": "&#x3A3;",
      "glyph": "Σ",
      "asciimath": "Sigma",
      "name": "capital sigma greek letter",
    },
    {
      "character": "&#x3C4;",
      "glyph": "τ",
      "asciimath": "tau",
      "name": "tau greek letter",
    },
    {
      "character": "&#x3C5;",
      "glyph": "υ",
      "asciimath": "upsilon",
      "name": "upsilon greek letter",
    },
    {
      "character": "&#x3D5;",
      "glyph": "ϕ",
      "asciimath": "phi",
      "name": "phi greek letter",
    },
    {
      "character": "&#x3A6;",
      "glyph": "Φ",
      "asciimath": "Phi",
      "name": "capital phi greek letter",
    },
    {
      "character": "&#x3C6;",
      "glyph": "φ",
      "asciimath": "varphi",
      "name": "varphi greek letter",
    },
    {
      "character": "&#x3C7;",
      "glyph": "χ",
      "asciimath": "chi",
      "name": "chi greek letter",
    },
    {
      "character": "&#x3C8;",
      "glyph": "ψ",
      "asciimath": "psi",
      "name": "psi greek letter",
    },
    {
      "character": "&#x3A8;",
      "glyph": "Ψ",
      "asciimath": "Psi",
      "name": "capital psi greek letter",
    },
    {
      "character": "&#x3C9;",
      "glyph": "ω",
      "asciimath": "omega",
      "name": "omega greek letter",
    },
    {
      "character": "&#x3A9;",
      "glyph": "Ω",
      "asciimath": "Omega",
      "name": "capital omega greek letter",
    },
  ]
